In [14]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split

In [15]:
data = pd.read_csv("emails.csv")
text = data[data.columns[0]]
spam = data[data.columns[1]]

In [16]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(text)
X_train_counts.shape

(5728, 37303)

In [17]:
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X_train_tf, spam, test_size = 0.20)

In [19]:
clf = LogisticRegression(solver='saga').fit(X_train, y_train)


In [20]:
count_vect.vocabulary_.get(u'aurora')

5715

In [21]:
clf.predict(X_train[:10])

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)

In [ ]:
clf.predict_proba(X_train[:10])

In [23]:
clf.score(X_train, y_train)

0.983195111305107

In [24]:
#Testando com a base de teste
clf.predict(X_test[:10])

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int64)

In [25]:
clf.predict_proba(X_test[:10])

array([[0.99392053, 0.00607947],
       [0.74534042, 0.25465958],
       [0.34148756, 0.65851244],
       [0.39737968, 0.60262032],
       [0.99123543, 0.00876457],
       [0.50032389, 0.49967611],
       [0.99299959, 0.00700041],
       [0.88509948, 0.11490052],
       [0.99443983, 0.00556017],
       [0.94153239, 0.05846761]])

In [26]:
clf.score(X_test, y_test)

0.9703315881326352